export const MOCK_DEPARTMENTS = [
  {
    id: 'dept-1',
    name: 'Ban Truyền thông',
    slug: 'truyen-thong',
    color: '#2563eb',
    description: 'Sáng tạo nội dung, thiết kế đồ họa, chụp ảnh, sản xuất video và quản lý truyền thông mạng xã hội của CLB.'
  },
  {
    id: 'dept-2',
    name: 'Ban Tư vấn',
    slug: 'tu-van',
    color: '#059669',
    description: 'Tư vấn hướng nghiệp, kết nối học bổng, hỗ trợ học tập và định hướng phát triển toàn diện cho sinh viên.'
  },
  {
    id: 'dept-3',
    name: 'Ban Nhân sự',
    slug: 'nhan-su',
    color: '#7c3aed',
    description: 'Quản trị nhân lực nội bộ, xây dựng văn hóa gắn kết thành viên, tổ chức tuyển sinh và vận hành hoạt động CLB.'
  },
]

export const MOCK_CANDIDATES = [
  {
    id: 'app-01',
    user_id: 'user-01',
    department_id: 'dept-1',
    status: 'finalized' as const,
    submitted_at: '2026-09-01T08:30:00Z',
    created_at: '2026-09-01T08:00:00Z',
    profiles: {
      full_name: 'Nguyễn Hà Phương',
      email: 'phuong.nguyen@vnu.edu.vn',
      student_id: '22070142',
      phone: '0987123456',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Hệ thống thông tin quản lý (MIS)',
      cohort: 'K22',
      gender: 'Nữ',
      cv_url: 'https://drive.google.com/sample_cv_phuong',
      facebook_url: 'https://facebook.com/haphuong.issac',
      gpa: 3.82,
      bio: 'Sáng tạo nội dung TikTok & Fanpage, từng làm Trưởng ban truyền thông Ngày hội Tân sinh viên VNU-IS.',
    },
    departments: { name: 'Ban Truyền thông', slug: 'truyen-thong' },
    candidate_rankings: { rank_number: 1, final_score: 9.6, result: 'pass' as const },
  },
  {
    id: 'app-02',
    user_id: 'user-02',
    department_id: 'dept-2',
    status: 'finalized' as const,
    submitted_at: '2026-09-01T09:15:00Z',
    created_at: '2026-09-01T08:30:00Z',
    profiles: {
      full_name: 'Trần Minh Hoàng',
      email: 'hoang.tran@vnu.edu.vn',
      student_id: '22070891',
      phone: '0912345678',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Kinh doanh Quốc tế (IB)',
      cohort: 'K22',
      gender: 'Nam',
      cv_url: 'https://drive.google.com/sample_cv_hoang',
      facebook_url: 'https://facebook.com/minhhoang.advisor',
      gpa: 3.75,
      bio: 'IELTS 8.0, kinh nghiệm tư vấn học bổng du học và hỗ trợ sinh viên quốc tế tại VNU-IS.',
    },
    departments: { name: 'Ban Tư vấn', slug: 'tu-van' },
    candidate_rankings: { rank_number: 2, final_score: 9.5, result: 'pass' as const },
  },
  {
    id: 'app-03',
    user_id: 'user-03',
    department_id: 'dept-3',
    status: 'finalized' as const,
    submitted_at: '2026-09-01T10:00:00Z',
    created_at: '2026-09-01T09:00:00Z',
    profiles: {
      full_name: 'Lê Thảo Linh',
      email: 'linh.le@vnu.edu.vn',
      student_id: '23070215',
      phone: '0978901234',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Quản trị Kinh doanh (EM)',
      cohort: 'K23',
      gender: 'Nữ',
      cv_url: 'https://drive.google.com/sample_cv_linh',
      facebook_url: 'https://facebook.com/thaolinh.hr',
      gpa: 3.88,
      bio: 'Kỹ năng quản trị nhân sự, lắng nghe, kết nối thành viên và điều phối nhân lực các sự kiện lớn.',
    },
    departments: { name: 'Ban Nhân sự', slug: 'nhan-su' },
    candidate_rankings: { rank_number: 3, final_score: 9.4, result: 'pass' as const },
  },
  {
    id: 'app-04',
    user_id: 'user-04',
    department_id: 'dept-1',
    status: 'finalized' as const,
    submitted_at: '2026-09-01T11:20:00Z',
    created_at: '2026-09-01T10:00:00Z',
    profiles: {
      full_name: 'Phạm Đăng Khoa',
      email: 'khoa.pham@vnu.edu.vn',
      student_id: '22070554',
      phone: '0934567890',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Marketing số',
      cohort: 'K22',
      gender: 'Nam',
      cv_url: 'https://drive.google.com/sample_cv_khoa',
      facebook_url: 'https://facebook.com/dangkhoa.design',
      gpa: 3.68,
      bio: 'Sử dụng thuần thục Adobe Illustrator, Photoshop, Figma. Có kinh nghiệm xây dựng bộ nhận diện CLB.',
    },
    departments: { name: 'Ban Truyền thông', slug: 'truyen-thong' },
    candidate_rankings: { rank_number: 4, final_score: 9.3, result: 'pass' as const },
  },
  {
    id: 'app-05',
    user_id: 'user-05',
    department_id: 'dept-2',
    status: 'finalized' as const,
    submitted_at: '2026-09-02T08:10:00Z',
    created_at: '2026-09-02T07:45:00Z',
    profiles: {
      full_name: 'Vũ Hải Yến',
      email: 'yen.vu@vnu.edu.vn',
      student_id: '23070388',
      phone: '0901234888',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Tài chính - Ngân hàng (Fintech)',
      cohort: 'K23',
      gender: 'Nữ',
      cv_url: 'https://drive.google.com/sample_cv_yen',
      facebook_url: 'https://facebook.com/haiyen.vu',
      gpa: 3.79,
      bio: 'Tự tin, nhiệt tình, có kinh nghiệm tư vấn định hướng môn học và hướng nghiệp sinh viên năm nhất.',
    },
    departments: { name: 'Ban Tư vấn', slug: 'tu-van' },
    candidate_rankings: { rank_number: 5, final_score: 9.2, result: 'pass' as const },
  },
  {
    id: 'app-06',
    user_id: 'user-06',
    department_id: 'dept-3',
    status: 'finalized' as const,
    submitted_at: '2026-09-02T09:30:00Z',
    created_at: '2026-09-02T09:00:00Z',
    profiles: {
      full_name: 'Đoàn Quốc Tuấn',
      email: 'tuan.doan@vnu.edu.vn',
      student_id: '22070441',
      phone: '0966554433',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Hệ thống thông tin quản lý',
      cohort: 'K22',
      gender: 'Nam',
      cv_url: 'https://drive.google.com/sample_cv_tuan',
      facebook_url: 'https://facebook.com/quoctuan.doan',
      gpa: 3.65,
      bio: 'Năng động, có kỹ năng tổ chức team bonding và đánh giá nhân sự theo KPI.',
    },
    departments: { name: 'Ban Nhân sự', slug: 'nhan-su' },
    candidate_rankings: { rank_number: 6, final_score: 9.1, result: 'pass' as const },
  },
  {
    id: 'app-07',
    user_id: 'user-07',
    department_id: 'dept-1',
    status: 'finalized' as const,
    submitted_at: '2026-09-02T14:15:00Z',
    created_at: '2026-09-02T13:30:00Z',
    profiles: {
      full_name: 'Hoàng Bích Ngọc',
      email: 'ngoc.hoang@vnu.edu.vn',
      student_id: '23070512',
      phone: '0944332211',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Marketing số',
      cohort: 'K23',
      gender: 'Nữ',
      cv_url: 'https://drive.google.com/sample_cv_ngoc',
      facebook_url: 'https://facebook.com/bichngoc.media',
      gpa: 3.85,
      bio: 'Sở trường viết bài PR truyền thông, lên kịch bản video ngắn và quản trị kênh mạng xã hội.',
    },
    departments: { name: 'Ban Truyền thông', slug: 'truyen-thong' },
    candidate_rankings: { rank_number: 7, final_score: 9.0, result: 'pass' as const },
  },
  {
    id: 'app-08',
    user_id: 'user-08',
    department_id: 'dept-2',
    status: 'finalized' as const,
    submitted_at: '2026-09-02T16:00:00Z',
    created_at: '2026-09-02T15:20:00Z',
    profiles: {
      full_name: 'Bùi Đức Anh',
      email: 'anh.bui@vnu.edu.vn',
      student_id: '22070629',
      phone: '0919876543',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Kinh doanh Quốc tế',
      cohort: 'K22',
      gender: 'Nam',
      cv_url: 'https://drive.google.com/sample_cv_ducanh',
      facebook_url: 'https://facebook.com/ducanh.bui',
      gpa: 3.72,
      bio: 'Khả năng giao tiếp thuyết phục, sẵn lòng hỗ trợ giải đáp thắc mắc cho tân sinh viên VNU-IS.',
    },
    departments: { name: 'Ban Tư vấn', slug: 'tu-van' },
    candidate_rankings: { rank_number: 8, final_score: 8.9, result: 'pass' as const },
  },
  {
    id: 'app-09',
    user_id: 'user-09',
    department_id: 'dept-3',
    status: 'finalized' as const,
    submitted_at: '2026-09-03T09:00:00Z',
    created_at: '2026-09-03T08:15:00Z',
    profiles: {
      full_name: 'Đặng Mai Chi',
      email: 'chi.dang@vnu.edu.vn',
      student_id: '23070774',
      phone: '0981122334',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Quản trị Kinh doanh',
      cohort: 'K23',
      gender: 'Nữ',
      cv_url: 'https://drive.google.com/sample_cv_maichi',
      facebook_url: 'https://facebook.com/maichi.dang',
      gpa: 3.76,
      bio: 'Cẩn thận, chu đáo, có trách nhiệm trong theo dõi chuyên cần và đánh giá thành viên.',
    },
    departments: { name: 'Ban Nhân sự', slug: 'nhan-su' },
    candidate_rankings: { rank_number: 9, final_score: 8.8, result: 'pass' as const },
  },
  {
    id: 'app-10',
    user_id: 'user-10',
    department_id: 'dept-1',
    status: 'finalized' as const,
    submitted_at: '2026-09-03T11:00:00Z',
    created_at: '2026-09-03T10:30:00Z',
    profiles: {
      full_name: 'Lý Gia Bảo',
      email: 'bao.ly@vnu.edu.vn',
      student_id: '22070198',
      phone: '0903344556',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Tin học & Kỹ thuật Máy tính',
      cohort: 'K22',
      gender: 'Nam',
      cv_url: 'https://drive.google.com/sample_cv_giabao',
      facebook_url: 'https://facebook.com/giabao.video',
      gpa: 3.66,
      bio: 'Quay dựng video clip recap sự kiện chuyên nghiệp với Premiere Pro và After Effects.',
    },
    departments: { name: 'Ban Truyền thông', slug: 'truyen-thong' },
    candidate_rankings: { rank_number: 10, final_score: 8.7, result: 'pass' as const },
  },
  {
    id: 'app-11',
    user_id: 'user-11',
    department_id: 'dept-2',
    status: 'finalized' as const,
    submitted_at: '2026-09-03T14:40:00Z',
    created_at: '2026-09-03T14:00:00Z',
    profiles: {
      full_name: 'Dương Khánh Huyền',
      email: 'huyen.duong@vnu.edu.vn',
      student_id: '23070832',
      phone: '0971239876',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Ngôn ngữ Anh & Quốc tế học',
      cohort: 'K23',
      gender: 'Nữ',
      cv_url: 'https://drive.google.com/sample_cv_khanhhuyen',
      facebook_url: 'https://facebook.com/khanhhuyen.duong',
      gpa: 3.82,
      bio: 'Tư vấn nhiệt tình, kỹ năng lắng nghe tốt, mong muốn đồng hành cùng các bạn sinh viên vượt qua khó khăn học tập.',
    },
    departments: { name: 'Ban Tư vấn', slug: 'tu-van' },
    candidate_rankings: { rank_number: 11, final_score: 8.6, result: 'pass' as const },
  },
  {
    id: 'app-12',
    user_id: 'user-12',
    department_id: 'dept-3',
    status: 'finalized' as const,
    submitted_at: '2026-09-03T16:15:00Z',
    created_at: '2026-09-03T15:45:00Z',
    profiles: {
      full_name: 'Phan Gia Huy',
      email: 'huy.phan@vnu.edu.vn',
      student_id: '22070337',
      phone: '0938877665',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Hệ thống thông tin quản lý',
      cohort: 'K22',
      gender: 'Nam',
      cv_url: 'https://drive.google.com/sample_cv_giahuy',
      facebook_url: 'https://facebook.com/giahuy.phan',
      gpa: 3.58,
      bio: 'Có kinh nghiệm tuyển dụng cộng tác viên và tổ chức các buổi sinh hoạt gắn kết CLB.',
    },
    departments: { name: 'Ban Nhân sự', slug: 'nhan-su' },
    candidate_rankings: { rank_number: 12, final_score: 8.5, result: 'pass' as const },
  },
  {
    id: 'app-13',
    user_id: 'user-13',
    department_id: 'dept-1',
    status: 'finalized' as const,
    submitted_at: '2026-09-04T08:45:00Z',
    created_at: '2026-09-04T08:00:00Z',
    profiles: {
      full_name: 'Ngô Trúc Quỳnh',
      email: 'quynh.ngo@vnu.edu.vn',
      student_id: '23070901',
      phone: '0961122445',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Marketing số',
      cohort: 'K23',
      gender: 'Nữ',
      cv_url: 'https://drive.google.com/sample_cv_trucquynh',
      facebook_url: 'https://facebook.com/trucquynh.ngo',
      gpa: 3.65,
      bio: 'Chụp ảnh sự kiện, có máy ảnh cá nhân, gu thẩm mỹ trẻ trung hợp xu hướng gen Z.',
    },
    departments: { name: 'Ban Truyền thông', slug: 'truyen-thong' },
    candidate_rankings: { rank_number: 13, final_score: 8.4, result: 'pass' as const },
  },
  {
    id: 'app-14',
    user_id: 'user-14',
    department_id: 'dept-2',
    status: 'finalized' as const,
    submitted_at: '2026-09-04T10:30:00Z',
    created_at: '2026-09-04T09:50:00Z',
    profiles: {
      full_name: 'Tạ Minh Trí',
      email: 'tri.ta@vnu.edu.vn',
      student_id: '22070477',
      phone: '0915566778',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Kinh doanh Quốc tế',
      cohort: 'K22',
      gender: 'Nam',
      cv_url: 'https://drive.google.com/sample_cv_minhtri',
      facebook_url: 'https://facebook.com/minhtri.ta',
      gpa: 3.62,
      bio: 'Am hiểu các chương trình đào tạo liên kết của VNU-IS, nhiệt tình hỗ trợ định hướng ngành học.',
    },
    departments: { name: 'Ban Tư vấn', slug: 'tu-van' },
    candidate_rankings: { rank_number: 14, final_score: 8.3, result: 'pass' as const },
  },
  {
    id: 'app-15',
    user_id: 'user-15',
    department_id: 'dept-3',
    status: 'finalized' as const,
    submitted_at: '2026-09-04T14:00:00Z',
    created_at: '2026-09-04T13:20:00Z',
    profiles: {
      full_name: 'Chu Ngọc Lan',
      email: 'lan.chu@vnu.edu.vn',
      student_id: '23070665',
      phone: '0948899001',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Quản trị Kinh doanh',
      cohort: 'K23',
      gender: 'Nữ',
      cv_url: 'https://drive.google.com/sample_cv_ngoclan',
      facebook_url: 'https://facebook.com/ngoclan.chu',
      gpa: 3.70,
      bio: 'Sắp xếp công việc khoa học, quản lý thời gian tốt và có tinh thần trách nhiệm cao.',
    },
    departments: { name: 'Ban Nhân sự', slug: 'nhan-su' },
    candidate_rankings: { rank_number: 15, final_score: 8.2, result: 'pass' as const },
  },
  {
    id: 'app-16',
    user_id: 'user-16',
    department_id: 'dept-1',
    status: 'evaluated' as const,
    submitted_at: '2026-09-04T15:30:00Z',
    created_at: '2026-09-04T15:00:00Z',
    profiles: {
      full_name: 'Lâm Văn Thắng',
      email: 'thang.lam@vnu.edu.vn',
      student_id: '22070112',
      phone: '0922334455',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Marketing số',
      cohort: 'K22',
      gender: 'Nam',
      cv_url: 'https://drive.google.com/sample_cv_vanthang',
      facebook_url: 'https://facebook.com/vanthang.lam',
      gpa: 3.48,
      bio: 'Kỹ năng thiết kế cơ bản, cần rèn luyện thêm kỹ năng teamwork.',
    },
    departments: { name: 'Ban Truyền thông', slug: 'truyen-thong' },
    candidate_rankings: { rank_number: 16, final_score: 7.9, result: 'waitlist' as const },
  },
  {
    id: 'app-17',
    user_id: 'user-17',
    department_id: 'dept-2',
    status: 'evaluated' as const,
    submitted_at: '2026-09-04T16:45:00Z',
    created_at: '2026-09-04T16:10:00Z',
    profiles: {
      full_name: 'Vương Bảo Châu',
      email: 'chau.vuong@vnu.edu.vn',
      student_id: '23070449',
      phone: '0977665544',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Kinh doanh Quốc tế',
      cohort: 'K23',
      gender: 'Nữ',
      cv_url: 'https://drive.google.com/sample_cv_baochau',
      facebook_url: 'https://facebook.com/baochau.vuong',
      gpa: 3.52,
      bio: 'Nhiệt tình nhưng còn rụt rè khi giao tiếp trước đám đông.',
    },
    departments: { name: 'Ban Tư vấn', slug: 'tu-van' },
    candidate_rankings: { rank_number: 17, final_score: 7.8, result: 'waitlist' as const },
  },
  {
    id: 'app-18',
    user_id: 'user-18',
    department_id: 'dept-3',
    status: 'evaluated' as const,
    submitted_at: '2026-09-05T09:00:00Z',
    created_at: '2026-09-05T08:30:00Z',
    profiles: {
      full_name: 'Đặng Tuấn Khang',
      email: 'khang.dang@vnu.edu.vn',
      student_id: '23070331',
      phone: '0933221100',
      university: 'Trường Quốc tế - ĐHQGHN (VNU-IS)',
      major: 'Quản trị Kinh doanh',
      cohort: 'K23',
      gender: 'Nam',
      cv_url: 'https://drive.google.com/sample_cv_tuankhang',
      facebook_url: 'https://facebook.com/tuankhang.dang',
      gpa: 3.35,
      bio: 'Có tinh thần học hỏi nhưng chưa có kinh nghiệm quản lý nhân sự.',
    },
    departments: { name: 'Ban Nhân sự', slug: 'nhan-su' },
    candidate_rankings: { rank_number: 18, final_score: 7.2, result: 'fail' as const },
  },
]

export const MOCK_INTERVIEW_SLOTS = [
  {
    id: 'slot-1',
    interview_date: '2026-09-12',
    start_time: '08:30',
    end_time: '10:00',
    format: 'offline' as const,
    location: 'Phòng Hội đồng 302, Nhà C, VNU-IS (Làng Sinh viên HACINCO)',
    meeting_url: null,
    max_candidates: 6,
    current_candidates: 6,
    is_active: true,
  },
  {
    id: 'slot-2',
    interview_date: '2026-09-12',
    start_time: '14:00',
    end_time: '15:30',
    format: 'offline' as const,
    location: 'Phòng Hội đồng 302, Nhà C, VNU-IS (Làng Sinh viên HACINCO)',
    meeting_url: null,
    max_candidates: 6,
    current_candidates: 5,
    is_active: true,
  },
  {
    id: 'slot-3',
    interview_date: '2026-09-13',
    start_time: '09:00',
    end_time: '10:30',
    format: 'online' as const,
    location: null,
    meeting_url: 'https://meet.google.com/iss-ac26-vnu',
    max_candidates: 5,
    current_candidates: 5,
    is_active: true,
  },
  {
    id: 'slot-4',
    interview_date: '2026-09-13',
    start_time: '14:30',
    end_time: '16:00',
    format: 'online' as const,
    location: null,
    meeting_url: 'https://meet.google.com/iss-ac26-vnu',
    max_candidates: 5,
    current_candidates: 2,
    is_active: true,
  },
]
